name: github checkout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 다른 사람이 만든 actions를 사용하고 싶을 때 uses 사용
      - uses: actions/checkout@v3 


      - name: 새 파일
        run: touch 
      - name: 커밋 & 푸시
        run: |
          git config --global user.name 'jun220' # 유저명
          git config --global user.email '152267292+jun220@users.noreply.github.com' # 유저 이메일
          git add -A
          git commit -am "auto update README.md" # 커밋 메시지
      - name: Push changes # 4) 메인에 푸시
        run: |
          git push
