name: github checkout

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 다른 사람이 만든 actions를 사용하고 싶을 때 uses 사용
     
      - uses: actions/checkout@v3 


      - name: Run pwd
        run: pwd
      - name: Run ls -al
        run: ls-al
